// ─────────────────────────────────────────────────────────────────────────────
//  Twilio Webhook Handler
//
//  Twilio calls this endpoint when a call arrives at your registered number.
//  Flow:
//    1. Parse caller/callee numbers from the webhook body
//    2. Look up the Business in the DB by the called number (multi-tenancy)
//    3. Check AMD (Answering Machine Detection) result from Twilio
//    4. Create a DB Call record + in-memory Session
//    5. Play Sesame greeting (cached) or redirect to /speak for generation
//
//  Greeting audio is generated by Sesame CSM and cached per-business. The
//  first call triggers generation (~8s) via <Redirect> to the speak handler.
//  Every subsequent call plays the cached audio instantly via <Play>.
// ─────────────────────────────────────────────────────────────────────────────

import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { sessionManager } from '@/lib/session-manager';
import { generateCallSummary } from '@/lib/claude/ai-agent';
import { getCachedGreeting, generateGreeting } from '@/lib/tts/sesame-client';
import { pendingAudio } from '@/lib/tts/pending-audio';
import { twiml, audioUrl } from '@/lib/telephony/twiml';
import type { LeadCriteria } from '@/types';

// ─── Inbound Voice Call ───────────────────────────────────────────────────────

export async function POST(req: NextRequest): Promise<NextResponse> {
  const formData   = await req.formData();
  const callSid    = formData.get('CallSid')    as string;
  const callStatus = formData.get('CallStatus') as string | null;

  // ── Route status callbacks (completed, failed, etc.) ──────────────────────
  //  Twilio sends ALL callbacks as POST. When CallStatus is a terminal state,
  //  this is a status callback — not a new incoming call.
  const terminalStatuses = ['completed', 'failed', 'busy', 'no-answer', 'canceled'];
  if (callStatus && terminalStatuses.includes(callStatus)) {
    return handleStatusCallback(formData, callSid, callStatus);
  }

  const callerNum  = formData.get('From')       as string;
  const calledNum  = formData.get('To')         as string;
  const answeredBy = formData.get('AnsweredBy') as string | null; // AMD result

  // ── Multi-tenant lookup ─────────────────────────────────────────────────────
  //
  //  First try to match by the called number directly. If no match is found,
  //  fall back to the most recently created active business. This handles the
  //  POC case where the Twilio platform number (from env) doesn't match the
  //  business's own phone number stored during onboarding.
  //
  let business = await prisma.business.findFirst({
    where: {
      phoneNumber: calledNum,
      isActive:    true,
    },
    include: { contextProfile: true },
  });

  if (!business) {
    business = await prisma.business.findFirst({
      where:   { isActive: true },
      include: { contextProfile: true },
      orderBy: { createdAt: 'desc' },
    });
  }

  if (!business || !business.contextProfile) {
    console.error(`[webhook] No configured business for ${calledNum}`);
    return twiml(`<Hangup/>`);
  }

  // ── Answering Machine Detection ─────────────────────────────────────────────
  //
  //  Twilio AMD fires AFTER the call is picked up. When AnsweredBy is not
  //  "human", we're talking to a machine — just hang up. Voicemail messages
  //  would require Polly or pre-generated Sesame audio; for now, skip.

  if (answeredBy && answeredBy !== 'human') {
    console.log(`[webhook] AMD detected machine for CallSid: ${callSid}`);
    return twiml(`<Hangup/>`);
  }

  // ── Create DB record ────────────────────────────────────────────────────────
  //  Use upsert to handle Twilio webhook retries (duplicate CallSid).
  await prisma.call.upsert({
    where: { twilioCallSid: callSid },
    update: { status: 'IN_PROGRESS', answeredAt: new Date() },
    create: {
      businessId:    business.id,
      twilioCallSid: callSid,
      callerNumber:  callerNum,
      status:        'IN_PROGRESS',
      direction:     'INBOUND',
      answeredAt:    new Date(),
    },
  });

  // ── Create in-memory session ────────────────────────────────────────────────
  sessionManager.createSession({
    callSid,
    businessId:   business.id,
    callerNumber: callerNum,
  });

  const greeting = business.contextProfile.greetingScript
    || `Thank you for calling ${business.name}. How can I assist you today?`;
  const lang  = business.contextProfile.language || 'en-US';
  const voice = business.contextProfile.voiceName || 'onyx';

  // Seed the greeting into conversation history so Claude knows it already spoke
  sessionManager.addMessage(callSid, 'assistant', greeting);

  // ── Play Sesame greeting ──────────────────────────────────────────────────
  //
  //  Check the on-disk greeting cache first. If cached, play it instantly.
  //  If not (first call for this business), kick off Sesame generation and
  //  redirect to the speak handler which gets its own fresh 15s clock.
  //
  //  <Play> is nested INSIDE <Gather> so callers can "barge in" — start
  //  speaking before the greeting finishes, which immediately stops playback
  //  and captures their speech.

  const cachedGreeting = getCachedGreeting(business.id, greeting, voice);

  if (cachedGreeting) {
    // Cache HIT — play pre-generated Sesame audio instantly
    const greetingUrl = audioUrl(req, cachedGreeting);

    console.log(`[webhook] Greeting cache HIT for ${business.name} — playing ${cachedGreeting}`);

    return twiml(`
      <Gather input="speech" action="/api/webhooks/twilio/gather" method="POST"
              speechTimeout="auto" timeout="8" language="${lang}">
        <Play>${greetingUrl}</Play>
      </Gather>
      <Hangup/>
    `);
  }

  // Cache MISS — first call for this business. Generate greeting with Sesame
  // and redirect to speak handler for a fresh 15s Twilio clock.
  console.log(`[webhook] Greeting cache MISS for ${business.name} — generating via Sesame`);

  const greetingPromise = generateGreeting(business.id, greeting, { voice });
  pendingAudio.set(callSid, {
    promise:         greetingPromise,
    fullText:        greeting,
    currentChunk:    greeting,
    remainingChunks: [],
    startedAt:       Date.now(),
    voice,
  });

  return twiml(`
    <Redirect method="POST">/api/webhooks/twilio/speak?lang=${encodeURIComponent(lang)}&amp;type=greeting</Redirect>
  `);
}

// ─── Status Callback (call lifecycle events from Twilio) ─────────────────────
//
//  Twilio sends these as POST with terminal CallStatus values.
//  Routed here from the POST handler above.

async function handleStatusCallback(
  formData: FormData,
  callSid: string,
  callStatus: string,
): Promise<NextResponse> {
  const duration = formData.get('CallDuration') as string | null;

  console.log(`[status] CallSid:${callSid} — ${callStatus} (${duration || '?'}s)`);

  const statusMap: Record<string, string> = {
    completed:   'COMPLETED',
    failed:      'FAILED',
    busy:        'BUSY',
    'no-answer': 'NO_ANSWER',
    canceled:    'FAILED',
  };

  await prisma.call.updateMany({
    where: { twilioCallSid: callSid },
    data: {
      status:   (statusMap[callStatus] ?? 'COMPLETED') as any,
      endedAt:  new Date(),
      duration: duration ? parseInt(duration, 10) : null,
    },
  });

  // ── Generate post-call summary (fire-and-forget) ──────────────────────────
  //
  //  Run this BEFORE ending the session so the conversation history is still
  //  available in memory. The summary, sentiment, lead score, and next action
  //  are persisted to the Call record for the dashboard.

  const session = sessionManager.getSessionByCallSid(callSid);
  if (session && session.conversationHistory.length > 0) {
    const business = await prisma.business.findUnique({
      where:   { id: session.businessId },
      include: { contextProfile: true },
    });

    if (business?.contextProfile) {
      const leadCriteria = (business.contextProfile.leadCriteria ?? {
        required: [], disqualifiers: [],
      }) as unknown as LeadCriteria;

      generateCallSummary(callSid, business.name, leadCriteria)
        .then(async (result) => {
          if (!result) return;
          await prisma.call.updateMany({
            where: { twilioCallSid: callSid },
            data: {
              summary:       result.summary,
              sentiment:     result.sentiment,
              leadScore:     result.leadScore,
              leadQualified: result.leadQualified,
              nextAction:    result.nextAction,
            },
          });
          console.log(`[summary] Generated for CallSid:${callSid} — score:${result.leadScore}`);
        })
        .catch((err) => console.error('[summary] Generation error:', err));
    }
  }

  sessionManager.endSession(callSid);
  return NextResponse.json({ ok: true });
}


